### ISSUE TITLE
Splits don't match Coldcard seeds

### ISSUE THREAD

**Issue by nervetrip** [AndreasGassmann/seed-xor#1]
It looks like this was based on [Coldcard's implementation](https://github.com/Coldcard/firmware/blob/master/shared/xor_seed.py). But when when I call `split` with the same 12 seed words as used on my Coldcard, I'm getting different split results. 

I was hoping this would deterministically create the same spits as CC given the same words. I know the readme says this is an early experiment, but I'm curious if this is a known issue, if there is something abnormal about my environmental, or if an exact match isn't a design goal.

**Comment by AndreasGassmann** [comment]
Hi. Yes, this library is supposed to work like the Coldcard implementation.

I took a quick look, and it seems that the deterministic creation of seeds isn't covered in the test cases. I only tested that it is deterministic within this library, so if you use a specific mnemonic with this library, it will always give you the same splits. But I didn't check it against the Coldcard implementation (even though I did follow their description [here](https://github.com/Coldcard/firmware/blob/master/docs/seed-xor.md)).

Could you, if you have some time, provide me with a test-mnemonic and the resulting splits if you do it with the Coldcard? Then I can check it against the library and fix it.

**Comment by nervetrip** [comment]
@AndreasGassmann 

# Example Mnemonic

Here's the example throwaway seed phrase I've been testing with:

`leisure twenty acoustic better student orient deer negative uniform enforce payment hill`

# This Library's Results 

This library results in the following SeedXOR values:

```
boss build candy theme pen case ranch client chimney spread behind frog mobile resist desert damp key indicate trumpet ski green bullet market strong

grain want cash void insect sausage match rice shell odor release curve
```

I found it unexpected that one is 24 words and the other is 12 words, as Coldcard resulted in 12 words for both splits. Note I'm calling this with `split(mnemonic)` and using default values for parameters 2 and 3. 

# ColdCard Results

Here's Coldcard's split values. I selected the repeatable deterministic approach, not the non-repeatable TRNG approach. 

```
happy lucky goddess element beach rare tackle island sniff melt blame gauge

blanket hurdle great fall series company tone tortoise cactus scene repair arctic
```

# Other considerations regarding ColdCard implementation

I've noticed some abnormalities in Coldcard's QRCode content. The text contained in the QRCodes for a seed phrase differs based on which part of the CC is used to display the QR.

For instance, when creating SeedXOR splits you can hit the QR button and display them as QRCodes. But these QRCodes contains word indexes instead of seed words. There is a possibility that Coldcard is using a numeric internal representation of the seed  phrase to generate the splits. Here are the text contents of the QRCodes that ColdCard displays for the SeedXOR splits of my test mnemonic seed phrase.

```
083910610801057301551424176809471643110901850772

018608920817065715680372182618360256154014600089
```

Furthermore, when I use the ColdCard to display the original test seed phrase as a QRCode, the contained text includes only the base 4 letters of each mnemonic. Again, there's the potential that CC is calculating SeedXOR based on an internal representation. Here's the QRCode contents for the test seed phrase:

`leis twen acou bett stud orie deer nega unif enfo paym hill`

As expected, when I attempt to use your library to split either of these style of representations, it throws an error.

```
const seeds = await split('leis twen acou bett stud orie deer nega unif enfo paym hill');
Error: [SeedXOR]: Invalid mnemonic
const seeds = await split('083910610801057301551424176809471643110901850772');
Error: [SeedXOR]: Invalid mnemonic
```

**Comment by AndreasGassmann** [comment]
Thank you for providing the additional information.

A few days ago I familiarised myself with the library again, and I do think that I found a few things:

- When looking at the commit hash of the ColdCard source code back when I implemented it, (https://github.com/Coldcard/firmware/blob/1c47b073fc933b2e216d73c980db9d3231b8dd30/shared/xor_seed.py#L73, they did not support 12 word mnemonics, which is why I didn't implement it.
- In the `getDeterministicEntropyFromMnemonic` method, I do not take the double sha256 as specified in the specs [see here](https://github.com/AndreasGassmann/seed-xor/blob/main/ts_src/utils.ts#L49)
- The `sha256` method in this library outputs a string and uses the string as an input for the second round, which results in a different result than taking the Buffer directly, so that is most likely a difference to the ColdCard implementation. [see here](https://github.com/AndreasGassmann/seed-xor/blob/main/ts_src/utils.ts#L19-L23)
- According to the docs here, [this](https://github.com/Coldcard/firmware/blob/1c47b073fc933b2e216d73c980db9d3231b8dd30/docs/seed-xor.md#xor-seed-example-using-3-parts) is how you calculate the shares deterministically:
> When shares are made deterministically, we take a double-SHA256 over a fixed string (`Batshitoshi`), your master secret, and the text `1 of 4 parts` which changes for each part.    

My expectation was that the final string would look something like this: `Batshitoshi 000000 1 of 4 parts`. However, looking at the ColdCard source code [here](https://github.com/Coldcard/firmware/blob/master/shared/xor_seed.py#L95-L96), the string will be `Batshitoshi 0000001 of 4 parts` (there is a space between the prefix and the seed, but not between the seed and the last part).
- I also noticed that in this library, I did a `+ 1` on the index of the share, probably to get a string like in the docs that says `1 of 4 parts` instead of starting at `0 of 4 parts`.

But even when taking all of this together, I was not able to reproduce the original splits (I used the example mnemonics they use in one of their [videos on youtube](https://www.youtube.com/watch?v=Vl1KHT_-h_Q).

I have also tried to find other libraries that implement this, but it seems that none of the libraries I found implemented the deterministic split as ColdCard did. I also tried to set up their local emulator to be able to log the intermediate steps, but I wasn't able to get it to work on my machine yet.

I'll take another look with examples and try to reproduce it. Thanks very much.

**Comment by AndreasGassmann** [comment]
I just remembered that I forgot to reply to your observations.

> ```
> const seeds = await split('leis twen acou bett stud orie deer nega unif enfo paym hill');
> Error: [SeedXOR]: Invalid mnemonic
> ```

Words in the BIP39 wordlist are uniquely identifiable by their first 4 characters. So they probably did this as an optimisation. So having `leis` as a "word", it's clear that it can only be `leisure`.

> ```
> const seeds = await split('083910610801057301551424176809471643110901850772');
> Error: [SeedXOR]: Invalid mnemonic
> ```

Yes, this looks like it's the index of the word in the BIP39 wordlist. If you take the first number of this input `0839` and check it against the list here (https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt), you will see that the word on line `840` is indeed `happy` (it's 1 more because the line numbers begin at 1, usually indexes begin at 0). You can also double check this with the following tool: https://iancoleman.io/bip39/ (do not enter production mnemonics there). You can paste in the mnemonic into the "BIP39 Mnemonic" field, then tick the box "Show entropy details", and you will see the exact numbers of this string in the "Word Indexes".

**Comment by nervetrip** [comment]
Great info, thanks for looking into it! 

I'm pretty sure you can ignore the **Other Considerations** I mentioned, as it is unlikely Coldcard stores wallets internally as mnemonics strings (or partial words or word indexes) instead of a rootKey or pub/prv keypair of some sort. I'm not at all familiar with their codebase, but just making assumptions.

**Comment by AndreasGassmann** [comment]
Good news, I found the issue. It was a combination of everything I mentioned, plus how the data was passed to the hashing function.

In the PR I created, both your case and the one I took from their video works. However the one from their docs doesn't. But I assume that's because it wasn't generated deterministically, but rather just to show how the xor works.

I also added some additional checks to make sure people don't misuse the library (eg. passing mnemonics of unsupported lengths).

Feel free to give it a try. In the next few days I'll create a new release and also update https://github.com/AndreasGassmann/seed-xor-hamming, which may also be affected by this.

Thanks again for bringing this to my attention!

**Comment by nervetrip** [comment]
@AndreasGassmann Nice work!

I just tested out your changes with the test case above as well as a 24 word test. I can confirm both now match the resulting SeedXOR produced by the ColdCard. 

I'm not familiar with seed-xor-hamming, I'll look into that more. Do you know of any wallets or products that support it?

**Comment by AndreasGassmann** [comment]
Great to hear, I just released `v0.0.2` with the changes.

I don't think the hamming variant is used by any wallet. But it is really interesting, because it works similar to seed-xor. Only the generation of the shares is done in a way that allows you to do a "2 of 3" recovery, so any 2 shares will combine back to the original one.

**Comment by nervetrip** [comment]
BTW, I copied the *.ts files from your dev branch into my project to test. I wasn't using a linked npm module. But I did have to change one line of code in `utils.ts` to get it working.

Changed from this: `import * as createHash from 'create-hash';`
To this: `import createHash from 'create-hash';`

**Comment by nervetrip** [comment]
> Great to hear, I just released `v0.0.2` with the changes.

Perfect, I'll try out the npm version. 

I wonder if you should bump the major (or at least minor version), since it seems like this is a breaking change. Although maybe there aren't enough users of this module yet to worry about it.

**Comment by AndreasGassmann** [comment]
You are probably right about the version, but that would have bumped it to 1.0.0. Maybe now that we tested it against the Coldcard I could do that, but then I should probably remove the disclaimer as well.

Personally I feel like if a package is below v1, breaking changes are expected.

I saw that bip39 updated their dependencies, I think I will also make those changes and may release the new version with a higher number, maybe even a 1.0.0 release. What do you think?

**Comment by nervetrip** [comment]
Good point - anything with a `0.0.x` version is definitely likely to have breaking changes.  You should make the call on what version to go with. I just wanted to point out the risk of breaking other people's apps. 

Personally, I fix dependency versions once I've reviewed the code for exploits so I don't accidentally install a "bad" version.
